name: ptype_stage1_full_am_co_sr_p_v1
particle: mixed_particle_type
root: E:/TimepixData/particle/datasets/particle_type_stage1_full_am_co_sr_p_v1
available_modalities: [ToT, ToA]
default_modalities: [ToT, ToA]
label_type: categorical_folder
sample_shape: [100, 100]
