name: ptype_stage1_gmm02_p_v5_cosr_removed
particle: mixed_particle_type
root: E:/TimepixData/particle/datasets/particle_type_stage1_full_am_co_sr_gmm_k3_label0_2_p_v5_cosr_all3_removed/dataset
available_modalities: [ToT, ToA]
default_modalities: [ToT, ToA]
label_type: categorical_folder
sample_shape: [100, 100]
